"""fuck

Revision ID: c9e5e66f270d
Revises: 
Create Date: 2025-01-04 15:56:19.522837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e5e66f270d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_x', sa.String(length=100), nullable=False),
    sa.Column('status_x', sa.Boolean(), nullable=False),
    sa.Column('in_room', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_room')
    # ### end Alembic commands ###
