"""delete some from preferences

Revision ID: f65638c473f7
Revises: 54f0b12aab66
Create Date: 2025-01-03 12:48:47.280668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65638c473f7'
down_revision: Union[str, None] = '54f0b12aab66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preference_hobby', 'user_id_x')
    op.drop_column('user_preferences', 'user_id_x')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('user_id_x', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user_preference_hobby', sa.Column('user_id_x', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
